### ISSUE TITLE
Training Mode Overhaul

### ISSUE THREAD

**Issue by Kikasuru** [Windblade-GR01/Ikemen-GO#137]
Hello!

Is there a way you could remove the restriction of only using the crappy training bot for training mode? This will allow for players to be able to practice against character specific tech and get the blocking frames for overheads. (Currently the bot doesn't block standing overheads at all.)

I also request, in replacement for the training bot, the functions are implemented into the engine. With the fact that it'll be software side instead of character side, there will be more power over how the second character behaves. (Being able to block overheads properly, use AI, maybe even have a dummy where it can record an action and play it back, etc.)

Thank you for your time.

**Comment by Windblade-GR01** [comment]
A training mode overhaul that is character independent is currently begin worked on by K4thos.

**Comment by EVILEDLIBRE** [comment]
That's good to hear. I also wanted to say that I think this is a good idea. I'm glad it's being worked on.

For the purpose of getting rid mugen dependencies; having to keep the training version of kung fu man around because the engine currently requires a training character to boot was something I was trying to think of a way around. Making it so that people can train with any character should allow for the removal of that boot requirement. Literally, that's the only reason I keep training kung fu man around.

Also, most fighting games no days allow you to select which character to train against. Different characters have different heights and stuff and so training against one static character does restrict training.

**Comment by Windblade-GR01** [comment]
So the training mode overhaul is in current versions.
Closing this.
