### ISSUE TITLE
3ha's Bishamon's HCF + Kicks super is broken

### ISSUE THREAD

**Issue by LasombraDemon** [Windblade-GR01/Ikemen-GO#194]
[BISHAMON.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/5550522/BISHAMON.zip)

In Mugen 1.0, this works properly. In IKEMEN, it sends the opponent flying away too high and never "releases" it.

MUGEN:
![mugen000](https://user-images.githubusercontent.com/74574875/99325195-90678780-2854-11eb-8c5b-59280596df9a.png)

IKEMEN:
![ikemen001](https://user-images.githubusercontent.com/74574875/99325192-8fcef100-2854-11eb-8190-e6540fb09a29.png)
![ikemen002](https://user-images.githubusercontent.com/74574875/99325187-8e052d80-2854-11eb-8399-207779ac8adf.png)
![ikemen003](https://user-images.githubusercontent.com/74574875/99325197-9198b480-2854-11eb-9a4c-9028e59bbfbd.png)

**Comment by K4thos** [comment]
I have very limited knowledge about mugen inner workings but what happens here doesn't make sense to me. CNS code: (with DisplayToClipboard addition)

```ini
[Statedef 3170]
type = U
movetype = H
physics = N
ctrl = 0
velset = 0, 0
sprpriority = 1

[State 3170, 1]
type = ChangeAnim2
trigger1 = Time = 0
value = 3190

[State 3170, 2]
type = LifeAdd
trigger1 = Time = 47
trigger2 = Time = 57
trigger3 = Time = 67
value = ifelse(Life > 80, -80, -(Life-1))

[State 3170, 3]
type = LifeAdd
trigger1 = Time = 117
value = -20

[State 3170, 3]
type = DisplayToClipboard
trigger1 = 1
text = "time = %d, Pos Y = %f, Vel Y = %f"
params = time, Pos Y, Vel Y

[State 3170, 4]
type = SelfState
trigger1 = time = 200
trigger1 = Pos Y > -20 &&  Vel Y > 0
value = 5100
```

Tested in mugen 1.1:
last frame of Kung Fu Man being custom stated:
![1](https://user-images.githubusercontent.com/8928195/99328628-c6b8fd00-287c-11eb-86dc-4bf744d4ca52.png)

and in the next frame he somehow enters state 5050:
![2](https://user-images.githubusercontent.com/8928195/99328674-dfc1ae00-287c-11eb-961a-321f096b83dc.png)

but I don't see anything in code that would make the KFM to exit custom state (time = 200 and Pos Y > -20 condition obviously didn't trigger since the time was 117)

**Comment by K4thos** [comment]
the problem is the commented out fail-safe to 5050 state that is meant to happen when helper dies before dropping its target:
```go
		if bt.hasTarget(c.id) {
			if bt.sf(CSF_destroy) {
				//c.selfState(5050, -1, -1, -1, false)
				c.setBindTime(0)
				return
			}
			if !math.IsNaN(float64(c.bindPos[0])) {
				c.setXV(c.facing * bt.facing * bt.vel[0])
			}
			if !math.IsNaN(float64(c.bindPos[1])) {
				c.setYV(bt.vel[1])
			}
		}
```
the problem is the commented out fail-safe to 5050 state that is meant to happen when helper dies before dropping its target:
```go
		if bt.hasTarget(c.id) {
			if bt.sf(CSF_destroy) {
				//c.selfState(5050, -1, -1, -1, false)
				c.setBindTime(0)
				return
			}
			if !math.IsNaN(float64(c.bindPos[0])) {
				c.setXV(c.facing * bt.facing * bt.vel[0])
			}
			if !math.IsNaN(float64(c.bindPos[1])) {
				c.setYV(bt.vel[1])
			}
		}
```
Not sure who made this change and what was the exact reasoning but according to Kamekaze current engine behaviour that forces authors to do custom states properly is a good thing, so we should consider making it optional (maybe const disabled by default?)
