### ISSUE TITLE
portraitscale code needs a little improvement.

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen-GO#197]
``portraitscale`` really needs an X, and Y Scale
Example: ``portraitscale = 1.0,1.0``

and some ``portraitscale.small`` so the small icons (e.g.: 25x25) icons can be resized.

**Comment by K4thos** [comment]
You're referring to this, right? https://github.com/K4thos/Ikemen_GO/wiki/Character-features#def_info_portraitscale
if yes than what you're requesting is already possible from within screenpack - each portrait can be resized with scale parameters on x and y axis there.

The linked parameter is mostly meant as a countermeasure for mugen behaviour that forces characters with higher localcoord to use larger portraits (for example see kfm720 that has 480x560 portrait size due to 1280x720 localcoord, instead of 120x140 like normal kfm)
