### ISSUE TITLE
randomselect not random

### ISSUE THREAD

**Issue by randomarcadedude** [Windblade-GR01/Ikemen-GO#203]
I've been using IkemenGo with 228 characters and I have a problem when pressing the random icon, it only cycles through 50 of the same characters. I've tested this by pressing random for an hour, and it's always combinations of those same characters. Is there a command or variable I can add to fix this or is it just a bug?

**Comment by K4thos** [comment]
tested with Duraceller KOF Anthology compilation with 673 characters. Random character selection running for about 20 min storing how many times each character was randomly selected: 
[table_print.txt](https://github.com/Windblade-GR01/Ikemen-GO/files/5625278/table_print.txt)
it's not enough observations to get a uniform distribution, but as you can see none of the characters has been skipped and distribution looks pretty good to me.

So I can see 3 explanations here:
1. It didn't work correctly on some older build you're using but works now (I've tested it on latest 0.96 build that will be released soon) - in such case there is no point to investigate it further,
2. You've added 'exclude' parameter to some characters (this makes them not random selectable)
3. You had a bad luck

-----------------
You can check if character is valid for random selection by creating "debug" directory in main ikemen folder. Start the game, close it and check the "debug/t_randomChars.txt" file. If the file has less than 228 rows than let us know. Delete "debug" directory after this test since it affects performance.
