### ISSUE TITLE
Character winpose music interferes with win quote screen music.

### ISSUE THREAD

**Issue by waspennator** [Windblade-GR01/Ikemen-GO#243]
Been trying this out lately and i've noticed that with some characters (Unsure if it's cause i'm using an older screenpack or not), if the winpose they play has music (The kind that briefly overrides the background music), then when it shifts to the win quote screen, the music that's supposed to play won't play at all.

**Comment by K4thos** [comment]
upload character that showcases the problem

**Comment by Retroid84** [comment]
I can confirm this issue too, it was fixed a few versions ago already but the latest release brought the bug back. Characters like Darth Vader who has a continuous breathing sound effect, their sounds don't end after the round is over so they end up playing over the victory screen instead of just ending. Other characters like Robocop who makes a beeping sound when he dies continue to play their sound clips over the victory screen too.

**Comment by waspennator** [comment]
Took some video footage with The_None's Butt-head character as demonstration, normally music should be playing on the win screen.


[Ikemen GO winscreen BGM bug.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6598708/Ikemen.GO.winscreen.BGM.bug.zip)

**Comment by K4thos** [comment]
no it shouldn't. Footage from mugen 1.1: 

https://user-images.githubusercontent.com/8928195/120918629-9e2c0f80-c6b5-11eb-8bf1-69ed8bd8eb34.mp4

@Retroid84, that should be already fixed in 0.96, so if you're on older version - update. If you want me to test it than upload that vader character. There are like 10 different Darth Vader characters released for mugen. I'm not going to download and test all of them.

**Comment by K4thos** [comment]
fixed
