### ISSUE TITLE
VSelect compatibility

### ISSUE THREAD

**Issue by CitrusHappy** [Windblade-GR01/Ikemen-GO#292]
VSelect is extremely useful for creating character selects. Can we make Ikemen GO compatible with the now heavily outdated VSelect or would be better to write a new program specifically for this engine? If so what language would it be written in?

**Comment by K4thos** [comment]
try converting sff file to winmugen format. Even winmugen screenpack in ikemen go uses newer sff versions which are likely not supported by this old tool. Although I have not tested it, so just guessing.

As for the question - it's not our job to make ikemen go compatible with VSelect. VSelect is not open source iirc, so we can't update it.

**Comment by CitrusHappy** [comment]
I think i will give a try creating a C# application for select editing specifically for this engine. This would give more accessibility to the engine.

**Comment by ssj17vegeta** [comment]
You said it in your original comment : VSelect is heavily outdated, plus it doesn't support the myriad of new features Ikemen Go provides. A new tool would be much more interesting.

**Comment by K4thos** [comment]
juste tested it and the tool still works fine on ikemen go. What you need to do is placing mugen.cfg file inside data directory with `motif` parameter pointing to correct system.def file. And if you want to see actual screenpack art you will have to convert screenpack sff file from 1.1 to 1.0 version, since the tool does not support former one (both screenpacks distributed with engine use 1.1 format)

**Comment by K4thos** [comment]
tunglashor released updated version of VSelect that support Ikemen GO and improves SFFv2 compatibility (it already supported it before, just had some problem with files generated with Fighter Factory)

https://mugenguild.com/forum/msg.2513563

**Comment by CitrusHappy** [comment]
wow good thing I didn't put too much time into recreating vselect, good to know tunglashor is active again.
