### ISSUE TITLE
Super move freezing the enemy.

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#308]
https://streamable.com/9z2g4o

Not much to say here, video tells it all.

Character: https://www.sendspace.com/file/9ofl3i

The move in question is qcfhcb+2Kick

**Comment by K4thos** [comment]
no idea what is causing this move to whiff. Here is what happens during problematic frame:
![ikemen002](https://user-images.githubusercontent.com/8928195/126861083-41c2e1f7-8aad-4ba0-929c-c03d22e15310.png)
enemy in target state ignores this hitdef for some reason
![ikemen003](https://user-images.githubusercontent.com/8928195/126861089-c343f8dd-f71d-48be-a196-00e8967d18f0.png)

Hitdef:
```ini
[State 210, 1]
type = HitDef
triggerall = !var(55)
trigger1 = anim = 3403 && animelem = 6
attr = S, HA
damage = floor(10*ifelse(var(56),1.25,1)),10
animtype = up
air.animtype = up;back
guardflag =
hitflag = MAF
priority = 3, Hit
sparkno = s17002+(var(31)*10000)
sparkxy = -20, -90
hitsound = s3+(var(32)*2),9
guardsound = s3+(var(32)*2), 13
guard.sparkno = s17502+(var(31)*10000)
ground.type = Low
pausetime = 2,4
guard.pausetime = 12,11
ground.slidetime = 17
ground.hittime = 17
guard.hittime = 17
guard.slidetime = 17
guard.ctrltime = 24
ground.velocity = 0,-10.8
guard.velocity = -10.1796875
air.type = High
air.velocity = 0,-10.8
air.hittime = 13
air.juggle = 0
getpower = 0,0
givepower = 16,16
id = 3400
chainid = 3400
fall = 1
air.fall = 1
kill = 0
ground.cornerpush.veloff = 0
guard.cornerpush.veloff = 0
air.cornerpush.veloff = 0
yaccel = 0.5
fall.recovertime = 50
```

**Comment by K4thos** [comment]
same thing happens in ikemen plus and old ikemen go versions, so it's not a regression

**Comment by K4thos** [comment]
summary of the problem investigation done on discord: https://discord.com/channels/233345562261323776/282927929548210177/868428175875661854

It seems like checking if `h.chainid < 0` (-1 being the default value) to determine if NotHitBy works is not how MUGEN works at all.

What happens here is that hitdef with an id of 3401, hits opponent even though it should whiff thanks to NotHitBy sctrl. In Ikemen NotHitBy was skipped due to `chainid` being set to 3400.

This ticket can be closed now. I've left a link to this it in commit that comments out problematic code (will be removed in future if this change won't lead to regressions).
