### ISSUE TITLE
Powermax variable like kof

### ISSUE THREAD

**Issue by leandrooffline** [Windblade-GR01/Ikemen-GO#370]
For example 3vs3:
first char 3 power bar max
second char 4 power bar max
last char 5 power bar max

**Comment by Windblade-GR01** [comment]
So I do not understand well the proposal.
Do you mean every char having a different non-shared powerbar in simul/tag modes?

**Comment by Adnan1091** [comment]
Nope, he says that when you get beaten in KoF, the next character gets an extra power bar.He wants it to be implemented in ikemen go.

**Comment by K4thos** [comment]
Unlike mugen, which requires patching characters, this feature is already possible to implement via CommonStates, globally, without workarounds, if you have basic cns/zss knowledge
https://github.com/K4thos/Ikemen_GO/wiki/Miscellaneous-Info/#common

I think this answer should be accepted as solution for this ticket (so that it can be closed). Otherwsie it will hang infinitely open since stuff like this is to game specific, not something that has a chance of ever being part of engine default feature set.

**Comment by leandrooffline** [comment]
Understanded, thanks guys.
