### ISSUE TITLE
Floor Explod Scale

### ISSUE THREAD

**Issue by Mark85Mete** [Windblade-GR01/Ikemen-GO#379]
![mugen000](https://user-images.githubusercontent.com/50754014/139532722-fff5b91e-1480-4ecd-9287-9f583b337040.png)
So this is Mugen version on how floor explod behaves and this is Ikemen version
![ikemen000](https://user-images.githubusercontent.com/50754014/139532736-c864540f-8d07-4b4c-9470-c4ce4193769d.png)
[HyperBGweird.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7448904/HyperBGweird.zip)

**Comment by K4thos** [comment]
I don't think it's bug since the same thing happens on mugen 1.1, And if that's the case it's a problem with how character is coded, not how the engine interprets it.

Screenshot made on stock mugen 1, Kung Fu Temple stage.
![mugen008](https://user-images.githubusercontent.com/8928195/139587287-dc782424-3a6a-4bf0-b08e-f6c121089d51.png)

**Comment by Windblade-GR01** [comment]
It works the same as Mugen 1.1.
So not a compatibility problem.
