### ISSUE TITLE
Sorry for my english, two things that i want to know about screenpack and char

### ISSUE THREAD

**Issue by VuDuc09** [Windblade-GR01/Ikemen-GO#394]
Firstly thanks for making ikemen it's great 

The second thing is can characters from mugen be added directly to ikemen? I tried 2 characters and both showed the same erroes: 
.\external\script\start.lua:1398: chars/Ryu/Ryu.def:
common1.cns
open common1.cns: The system cannot find the file specified.
stack traceback:
	[G]: in function 'game'
	.\external\script\start.lua:1398: in function 'f_game'
	.\external\script\start.lua:1815: in function 'launchFight'
	external/script/default.lua:2: in function <external/script/default.lua:0>
	.\external\script\start.lua:1451: in function 'f'
	external/script/main.lua:2983: in function 'loop'
	external/script/main.lua:3103: in function 'loop'
	external/script/main.lua:4081: in main chunk
	[G]: ?

As far as I know, the characters in ikemen have switched to zss, how do I switch from cns to zss ?

Third, I tried using a very famous screenpack called legacy by Noz's. It works perfectly on ikemen but what bothers me a bit is that the menu screen doesn't have any ikemen game modes (especially multiplayer) maybe because I copied the files from the data ,char, sound, stage. I tried looking at the legacy system.def file and also the repo, it has too much to tweak to include ikemen game modes. Can you guys help me, at least add the network mode option to the menu or you can comment in the system.def file so that me and those new to ikemen Go can be easier to install screenpack.

Last thing, other than github, is there any community for people new to ikemen ko, such as discord. Please let me know. 

Screenpack and char file: [Here](https://drive.google.com/drive/folders/1DRqC4Tlrt8Sj_UbdeZP1oCsnVI3OJYC6?usp=sharing)

**Comment by Orochikyocr** [comment]
You don't have to switch anything. ZSS is merely optional. You are getting that error because those chars have their own common1.cns probably or when you installed your screenpack you maybe overwrite or delete the default common1.cns.zss of Ikemen Go
I can't think of an easier way to set up a screenpack for Ikemen Go to copy and paste the Ikemen go exclusive features into your screenpack.
If you are having a hard time setting up the screenpack the discord server has some screenpacks ready to go for Ikemen GO using the full features of the engine.
Everything in life is baby steps, try to add those chars first to a clean build of Ikemen go using the default screenpack. Then once chars are set up try to install the screenpack in a folder inside the data folder, don't overwrite the data folder files.
If you get the help needed to run your installation, please close this issue once you get everything running. 

This is the official Ikemen discord.
https://discord.gg/3uqNXuW8

**Comment by VuDuc09** [comment]
thank you so much, i'll try its

**Comment by VuDuc09** [comment]
That work thank you so much, about the screenpack i will try little by little.
