### ISSUE TITLE
Storyboard issue for KAZ's Cyclops.

### ISSUE THREAD

**Issue by carlosspeed15** [Windblade-GR01/Ikemen-GO#396]
So I have this problem when I was playing arcade mode with Cyclops from KAZ who has a storyboard inside the character file. After complete Arcade the game supposed to show Cyclops End story, however the engine crash and give the following error message.
![Screenshot (34)](https://user-images.githubusercontent.com/87279994/142934669-542bcfa9-f335-47f6-a1a6-6e2b904ccb7d.png)
This is probably an incompatibility issue.

**Comment by K4thos** [comment]
based on my tests this is not an ikemen issue. This storyboard SFF file seems corrupted. At least for the version of character you've uploaded on discord: https://drive.google.com/file/d/11f3e82CcrUAWI_AX9a9ES0ORZsxH3frE/view?usp=sharing 

it crashes mugen 1.0 with following error:
![2021-11-22](https://user-images.githubusercontent.com/8928195/142943328-f84e4ccd-4d81-4a16-80f7-504d033a335e.png)

And for mugen 1.1, whole storyboard is skipped (so again it fails to load SFF)

Tested by assigning this stoyrboard to character's intro instead of ending.

**Comment by K4thos** [comment]
I've made the error messages more informative (now the error says what file couldn't be loaded, alongside actual error message).
![2021-11-23](https://user-images.githubusercontent.com/8928195/142953379-845e4e5b-208c-4190-98c6-f4b835857c44.png)

Other than this I don't see anything here that requires changing since it seems to match mugen behaviour.

**Comment by carlosspeed15** [comment]
Thx for the info K4thos, it turns out I have to download the winmugen version of Cyclops for the storyboard works properly.
