### ISSUE TITLE
Perfect triggering while not full health on Turns.

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#423]
https://user-images.githubusercontent.com/77592586/150003215-14dc2bb3-0787-4cf5-949c-ed02644518b6.mp4

Not much to add here I think, works fine on single.

**Comment by UrsoManso** [comment]
[lifebar+char.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7892298/lifebar%2Bchar.zip)

This should be enough to reproduce the issue. About code block I have idea, but I've tested on a clean build myself and it seems that the problem might be related to the health restoring right after the KO.

**Comment by K4thos** [comment]
uploaded package is not enough to reproduce it on clean build. Perfect message doesn't show up at all.

**Comment by K4thos** [comment]
I wasn't able to reproduce it at first due to missing 2002um.cns in your package, but I had that file from previous upload.

The problem here was life recovery starting as soon as the roundstate = 4. In mugen it happens once character is forced into win state (which can be delayed betond roundstate 4 initial frame). I've changed it to work the same way, so reported issue should be gone in next build.
