### ISSUE TITLE
So what is HiscoreBGdef?

### ISSUE THREAD

**Issue by sakada91** [Windblade-GR01/Ikemen-GO#426]
i want to make the HiscoreBGdef but i don't know to do it

**Comment by K4thos** [comment]
exactly the same way as stage backgrounds which are fully documented by Elecbyte: http://www.elecbyte.com/mugendocs/bgs.html#description-of-background-elements
Defined in system.def under [HiscoreBGdef]

**Comment by sakada91** [comment]
ok but how do i mute the music when Here Comes A New Challenger is on?

**Comment by K4thos** [comment]
Answer - there is no such option.

Hint for a future - this ticket should have been closed by yourself after receiving a reply that answered your question (otherwise it's extra work for maintainer to close it down the road). Also github issues page is not really a good place for asking general questions about the engine. Please consider using other channels like discord server or MFG forums.

**Comment by sakada91** [comment]
well i have to edit the engine my myself

**Comment by sakada91** [comment]
or wait
